# Generated by Django 4.2.5 on 2023-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Ingrese la fecha de nacimiento en formato dd-mm-aaaa', verbose_name='Fecha de nacimiento'),
        ),
    ]
